name: nordic_nrf_mesh
description: A Flutter plugin to enable mesh network management and communication using Nordic Semiconductor's SDKs.
version: 0.12.0
homepage: https://www.dooz-domotique.com/
repository: https://github.com/OZEO-DOOZ/nrf_mesh_plugin
issue_tracker: https://github.com/OZEO-DOOZ/nrf_mesh_plugin/issues

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  # BLE handling
  flutter_reactive_ble: ^4.0.1
  rxdart: ^0.27.3
  retry: ^3.1.0
  # Models
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  # static analysis
  flutter_lints: ^1.0.4
  meta: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  json_serializable: ^6.1.5
  freezed: ^1.1.1

flutter:
  plugin:
    platforms:
      android:
        package: fr.dooz.nordic_nrf_mesh
        pluginClass: NordicNrfMeshPlugin
      ios:
        pluginClass: NordicNrfMeshPlugin
